function magnitude_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load magnitude_fig                     

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Name','Magnitude, 0 dB is max. level @ 1kHz from SNR&THR figure', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[26 28 529 299], ...
	'Tag','magnitude_fig');
b = axes('Parent',a, ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'Position',[0.0567108 0.0668896 0.931947 0.909699], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'XGrid','on', ...
	'YColor',[0 0 0], ...
	'YGrid','on', ...
	'ZColor',[0 0 0], ...
	'ZGrid','on');
