function oae_subject_browser_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load oae_subject_browser_fig           

a = figure('Color',[0.75 0.75 0.75], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name','OAE Subject Browser', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[0 0 425 460], ...
	'Resize','off', ...
	'Tag','Fig4');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[297 215 125 243], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Callback','oae_subject_browser help', ...
	'Position',[226 216 60 20], ...
	'String','Help', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Callback','oae_subject_browser new', ...
	'HorizontalAlignment','left', ...
	'Position',[226 369 60 20], ...
	'String','<- New   ', ...
	'Tag','Pushbutton2', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Callback','oae_subject_browser delete', ...
	'HorizontalAlignment','left', ...
	'Position',[226 342 60 20], ...
	'String','<- Delete', ...
	'Tag','delete');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Position',[23 446 130 16], ...
	'String','Surname_Prename', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oae_subject_browser fill', ...
	'Position',[4 216 205 232], ...
	'Style','listbox', ...
	'Tag','subjects', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Position',[237 191 40 16], ...
	'String','Phone:', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oae_subject_browser save', ...
	'HorizontalAlignment','left', ...
	'Position',[58 189 82 20], ...
	'Style','edit', ...
	'Tag','born');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oae_subject_browser save', ...
	'HorizontalAlignment','left', ...
	'Position',[296 188 127 20], ...
	'Style','edit', ...
	'Tag','phone');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Max',15, ...
	'Position',[5 148 80 16], ...
	'String','Comments:', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Position',[5 166 53 16], ...
	'String','Address:', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oae_subject_browser save', ...
	'HorizontalAlignment','left', ...
	'Max',2, ...
	'Position',[58 166 365 20], ...
	'Style','edit', ...
	'Tag','address');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oae_subject_browser save', ...
	'HorizontalAlignment','left', ...
	'Max',9, ...
	'Position',[4 3 420 147], ...
	'Style','edit', ...
	'Tag','comment');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Position',[5 189 53 16], ...
	'String','Born:', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','oae_subject_browser radiobutton_press', ...
	'HorizontalAlignment','left', ...
	'Position',[309 338 73 20], ...
	'String','TEOAE:', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1');
b = uicontrol('Parent',a, ...
	'Callback','oae_subject_browser browse', ...
	'Position',[226 437 60 20], ...
	'String','Browse ->', ...
	'Tag','view');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[388 386 24 20], ...
	'Style','text', ...
	'Tag','n_lf_ag');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','oae_subject_browser radiobutton_press', ...
	'HorizontalAlignment','left', ...
	'Position',[309 386 73 20], ...
	'String','LF_AG:', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[388 338 24 20], ...
	'Style','text', ...
	'Tag','n_teoae');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','oae_subject_browser radiobutton_press', ...
	'HorizontalAlignment','left', ...
	'Position',[309 362 73 20], ...
	'String','DPOAE:', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[388 362 24 20], ...
	'Style','text', ...
	'Tag','n_dpoae');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[388 410 24 20], ...
	'Style','text', ...
	'Tag','n_dp_tt');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'Position',[388 434 24 20], ...
	'Style','text', ...
	'Tag','n_audiogram');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','oae_subject_browser radiobutton_press', ...
	'HorizontalAlignment','left', ...
	'Position',[309 410 73 20], ...
	'String','DP_TT:', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','oae_subject_browser radiobutton_press', ...
	'HorizontalAlignment','left', ...
	'Position',[309 434 73 20], ...
	'String','PTAud:', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1');
