function stop_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load stop_fig                          

a = figure('Color',[0.752941 0.752941 0.752941], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name','Stop', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[100 100 320 25], ...
	'Resize','off', ...
	'Tag','continue');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize',13.1147, ...
	'ForegroundColor',[1 0 0], ...
	'Position',[8 6 230 20], ...
	'String','Press this button to stop measurement:', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','stop stop', ...
	'FontSize',10.6667, ...
	'Position',[254 6 63 20], ...
	'String','Stop', ...
	'Tag','Pushbutton1');
