function a = dp_tt_calibration_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load dp_tt_calibration_fig             

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'DeleteFcn','dp_tt_calibration close', ...
	'MenuBar','none', ...
	'Name','DP_TT Calibration', ...
	'NumberTitle','off', ...
	'PaperType','a4letter', ...
	'PointerShapeCData',mat1, ...
	'Position',[0 0 435 390], ...
	'Resize','off', ...
	'Tag','dp_tt_calibration_fig');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize',10.6667, ...
	'Position',[5 191 429 197], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize',10.6667, ...
	'Position',[5 4 429 184], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize',10.6667, ...
	'Max',3, ...
	'Position',[11 157 125 28], ...
	'String','           this calibration as reference! Variable Name:', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',10.6667, ...
	'HorizontalAlignment','left', ...
	'Position',[141 161 290 24], ...
	'Style','edit', ...
	'Tag','new_name');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','dp_tt_calibration fill', ...
	'FontSize',10.6667, ...
	'HorizontalAlignment','left', ...
	'Position',[140 334 291 51], ...
	'Style','listbox', ...
	'Tag','references', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_calibration ok', ...
	'FontSize',10.6667, ...
	'Position',[380 137 50 20], ...
	'String','OK', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_calibration save', ...
	'FontSize',10.6667, ...
	'Position',[11 169 37 17], ...
	'String','save', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_calibration delete_reference', ...
	'FontSize',10.6667, ...
	'Position',[85 335 48 16], ...
	'String','Delete:', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_calibration plot', ...
	'FontSize',10.6667, ...
	'Position',[272 137 50 20], ...
	'String','Plot', ...
	'Tag','plot');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','dp_tt_calibration comment', ...
	'HorizontalAlignment','left', ...
	'Max',12, ...
	'Position',[10 6 420 128], ...
	'Style','edit', ...
	'Tag','comment');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize',14, ...
	'HorizontalAlignment','left', ...
	'Position',[11 358 117 29], ...
	'String','Reference', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Position',[13 331 59 14.6667], ...
	'String','Comment:', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'HorizontalAlignment','left', ...
	'Position',[12 137 59 12], ...
	'String','Comment:', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[1 1 1], ...
	'Callback','dp_tt_calibration ref_comment', ...
	'HorizontalAlignment','left', ...
	'Max',12, ...
	'Position',[10.3333 195.667 420 136], ...
	'Style','edit', ...
	'Tag','ref_comment');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_calibration retry', ...
	'FontSize',10.6667, ...
	'Position',[327 137 50 20], ...
	'String','Start', ...
	'Tag','retry');
