function dp_tt_probe_check_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load dp_tt_probe_check_fig             

a = figure('Color',[0.752941 0.752941 0.752941], ...
    'Colormap',mat0, ...
    'BusyAction','cancel',...
    'Name','DP_TT Probe Check finished. OK or RETRY?', ...
    'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[0 0 563 395], ...
	'Tag','dp_tt_probe_check_fig');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_probe_check help;', ...
	'FontSize',10.6667, ...
	'Position',[8 8 60 20], ...
	'String','Help', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'FontUnits','pixels', ...
    'BusyAction','cancel',...
	'Callback','dp_tt_probe_check retry;', ...
	'FontSize',10.6667, ...
	'Position',[420 9 60 20], ...
	'String','Retry', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
    'BusyAction','cancel',...
	'FontUnits','pixels', ...
	'Callback','dp_tt_probe_check ok;', ...
	'FontSize',10.6667, ...
	'Position',[494 9 60 20], ...
	'String','OK', ...
	'Tag','Pushbutton1');
b = axes('Parent',a, ...
	'Units','normalized', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'Position',[0.06 0.57 0.94 0.43], ...
	'Tag','axes_magnitude', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
b = axes('Parent',a, ...
	'Units','normalized', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat3, ...
	'Position',[0.06 0.134 0.94 0.43], ...
	'Tag','axes_phase', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
