function fig = dp_tt_measurement_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load dp_tt_measurement_fig

h0 = figure('Color',[0.752941 0.752941 0.752941], ...
	'Colormap',mat0, ...
	'DeleteFcn','dp_tt_measurement close', ...    %'FileName','C:\home\Grobi\OAE\Dp_tt\dp_tt_measurement_fig.m', ...
    'MenuBar','none', ...
	'Name','dp_tt Measurement: tst', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperType','a4letter', ...
	'PaperUnits','points', ...
	'Position',[0 0 525 419], ...
	'Resize','off', ...
	'Tag','dp_tt_measurement_fig'); % , ...    %'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','dp_TT_measurement browse', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[4 393 519 25], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_measurement measure', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[21 13 60 20], ...
	'String','Measure', ...
	'Tag','Pushbutton1', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_measurement calibration', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[19 67 60 20], ...
	'String','Calibrate', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[4 152 100 20], ...
	'String','Comment:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[161 372 62 13], ...
	'String','Average [s]:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[5 295 100 20], ...
	'String','Frequencies f2 [Hz]:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[5 271 100 20], ...
	'String','Levels l2 [dB]:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[5 247 100 20], ...
	'String','BT frequencies [Hz]', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[5 223 100 20], ...
	'String','BT levels [dB]', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Max',12, ...
	'Position',[107 6 413 167], ...
	'Style','edit', ...
	'Tag','comment');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[225 369 30 20], ...
	'Style','edit', ...
	'Tag','t_avg');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 298 413 20], ...
	'Style','edit', ...
	'Tag','F2');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 273 413 20], ...
	'Style','edit', ...
	'Tag','L2');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 250 413 20], ...
	'Style','edit', ...
	'Tag','F_TT');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 226 413 20], ...
	'Style','edit', ...
	'Tag','L_TT');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[109 370 39 20], ...
	'Style','edit', ...
	'Tag','created');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[7 367 100 20], ...
	'String','Created by:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_measuremet help', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[19 94 60 20], ...
	'String','Help', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[400 369 80 20], ...
	'String',' Nested', ...
	'Style','checkbox', ...
	'Tag','nested_mode');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 322 413 20], ...
	'Style','edit', ...
	'Tag','L1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','set(findobj(gcbf,''Tag'',''defaults''),''String'',''NONE''),', ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 346 413 20], ...
	'Style','edit', ...
	'Tag','F1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[4 319 100 20], ...
	'String','Lev. l1 = l2+x ;  x=:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[4 343 100 20], ...
	'String','Freq. f1 = f2/x;  x=:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_measurement browse', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[472 395 48 20], ...
	'String','Browse', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[107 396 362 20], ...
	'Style','edit', ...
	'Tag','defaults');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontUnits','pixels', ... 
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[29 400 77 15], ...
	'String','Current Default:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'FontUnits','pixels', ...
	'Callback','dp_tt_measurement probe_fit', ...
	'FontSize' ,10.6667, ...
	'ListboxTop',0, ...
	'Position',[10 120 90 20], ...
	'String','Fit Tones: On', ...
	'Tag','probe_fit', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','dp_tt_measurement ear_l', ...
	'ListboxTop',0, ...
	'Position',[295 370 40 20], ...
	'String','left', ...
	'Style','radiobutton', ...
	'Tag','ear_l');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','dp_tt_measurement ear_r', ...
	'ListboxTop',0, ...
	'Position',[340 370 50 20], ...
	'String','right', ...
	'Style','radiobutton', ...
	'Tag','ear_r');
h1 = uicontrol('Parent',h0, ...
	'FontUnits','pixels', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'FontSize' ,10.6667, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[263 366 25 20], ...
	'String','Ear:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','pixels', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontUnits','pixels', ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[10 40 90 20], ...
	'String','Probe Check', ...
	'Style','checkbox', ...
	'Tag','probe_check', ...
	'Value',1);
if nargout > 0, fig = h0; end
