function a = viewer_magn_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load viewer_magn_fig                   

a = figure('Color',[0.8 0.8 0.8], ...
	'Toolbar','none', ...
	'Colormap',mat0, ...
	'NumberTitle','off', ...
	'PaperType','a4letter', ...
	'PointerShapeCData',mat1, ...
	'Position',[427 768 640 216], ...
	'Tag','plot');
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
    'Position',[0.044 0.1 0.95 0.82], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
