function  a = viewer_cmplx_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load viewer_cmplx_fig                  

a = figure('Color',[0.8 0.8 0.8], ...
	'Toolbar','none', ...
	'Colormap',mat0, ...
	'NumberTitle','off', ...
	'Name','DP_TT_cmplx: Nr.3, Ord. 4, marqua , 03-Jun-1998 20:47:26', ...
	'PaperType','a4letter', ...
	'PointerShapeCData',mat1, ...
	'Position',[1067 768 213 216], ...
	'Tag','plot');
