function a = viewer_phase_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load viewer_phase_fig                  

a = figure('Color',[0.8 0.8 0.8], ...
	'Toolbar','none', ...
	'Colormap',mat0, ...
	'Name','DP_TT_phase: Nr.3, Ord. 4, marqua , 03-Jun-1998 20:47:26', ...
	'NumberTitle','off', ...
	'PaperType','a4letter', ...
	'PointerShapeCData',mat1, ...
	'Position',[711 768 356 216], ...
	'Tag','plot');
b = axes('Parent',a, ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'Position',[0.1 0.1 0.90 0.82], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
